In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder

C:\Users\User\anaconda3\lib\site-packages\scipy\__init__.py:173: UserWarning: A NumPy version >=1.19.5 and <1.27.0 is required for this version of SciPy (detected version 1.19.2)
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [2]:
urldata = pd.read_csv('../data/processed_IEEEData.csv')

In [3]:
urldata

index                                                url  label
0      30845  belajarprogramming.com/newpaypal/loggy/paypal.htm      1
1      25750                     ninedotlabs.com/att2/index.php      1
2      91832                     www.almostfabulous.com/youker/      0
3      29165  stbcomputer.com/autodesk/components/www.paypal...      1
4      52012                     members.tripod.com/chang.ling/      0
...      ...                                                ...    ...
95777  86523                       www.winehq.com/?interview=14      0
95778  45352                                     2933517.com/js      1
95779  34852  imajinsmiles.com/Questions.html?cmd=_Questions...      1
95780   7754  thesecondhalfonline.com/wp-includes/js/tinymce...      1
95781  79751  www.informationweek.com/whitepaper/index.jhtml...      0

[95782 rows x 3 columns]

In [4]:
urldata['m_url'] = urldata['url'].apply(lambda i: i)

for x in range(len(urldata['url'])):
    t = urldata['url'][x]
    if not (t.startswith('http://') or t.startswith('https://') or t.startswith('ftp://')):
        urldata['m_url'][x] = 'http://' + urldata['url'][x]

<ipython-input-4-a9de932e6da7>:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  urldata['m_url'][x] = 'http://' + urldata['url'][x]


In [5]:
urldata

index                                                url  label  \
0      30845  belajarprogramming.com/newpaypal/loggy/paypal.htm      1   
1      25750                     ninedotlabs.com/att2/index.php      1   
2      91832                     www.almostfabulous.com/youker/      0   
3      29165  stbcomputer.com/autodesk/components/www.paypal...      1   
4      52012                     members.tripod.com/chang.ling/      0   
...      ...                                                ...    ...   
95777  86523                       www.winehq.com/?interview=14      0   
95778  45352                                     2933517.com/js      1   
95779  34852  imajinsmiles.com/Questions.html?cmd=_Questions...      1   
95780   7754  thesecondhalfonline.com/wp-includes/js/tinymce...      1   
95781  79751  www.informationweek.com/whitepaper/index.jhtml...      0   

                                                   m_url  
0      http://belajarprogramming.com/newpaypal/loggy/...  
1                  http://ninedotlabs.com/att2/index.php  
2                  http://www.almostfabulous.com/youker/  
3      http://stbcomputer.com/autodesk/components/www...  
4                  http://members.tripod.com/chang.ling/  
...                                                  ...  
95777                http://www.winehq.com/?interview=14  
95778                              http://2933517.com/js  
95779  http://imajinsmiles.com/Questions.html?cmd=_Qu...  
95780  http://thesecondhalfonline.com/wp-includes/js/...  
95781  http://www.informationweek.com/whitepaper/inde...  

[95782 rows x 4 columns]

In [6]:
#Divide the URL into three parts: (1) subdomain/domain (2) path/file (3) query
#Importing dependencies
from urllib.parse import urlparse
import os.path

#find out the hostname from the url
urldata['hostname'] = urldata['m_url'].apply(lambda i: urlparse(i).netloc)

#find out the path from the url
urldata['path'] = urldata['m_url'].apply(lambda i: urlparse(i).path)

urldata['query'] = urldata['m_url'].apply(lambda i: urlparse(i).query)

In [7]:
urldata

index                                                url  label  \
0      30845  belajarprogramming.com/newpaypal/loggy/paypal.htm      1   
1      25750                     ninedotlabs.com/att2/index.php      1   
2      91832                     www.almostfabulous.com/youker/      0   
3      29165  stbcomputer.com/autodesk/components/www.paypal...      1   
4      52012                     members.tripod.com/chang.ling/      0   
...      ...                                                ...    ...   
95777  86523                       www.winehq.com/?interview=14      0   
95778  45352                                     2933517.com/js      1   
95779  34852  imajinsmiles.com/Questions.html?cmd=_Questions...      1   
95780   7754  thesecondhalfonline.com/wp-includes/js/tinymce...      1   
95781  79751  www.informationweek.com/whitepaper/index.jhtml...      0   

                                                   m_url  \
0      http://belajarprogramming.com/newpaypal/loggy/...   
1                  http://ninedotlabs.com/att2/index.php   
2                  http://www.almostfabulous.com/youker/   
3      http://stbcomputer.com/autodesk/components/www...   
4                  http://members.tripod.com/chang.ling/   
...                                                  ...   
95777                http://www.winehq.com/?interview=14   
95778                              http://2933517.com/js   
95779  http://imajinsmiles.com/Questions.html?cmd=_Qu...   
95780  http://thesecondhalfonline.com/wp-includes/js/...   
95781  http://www.informationweek.com/whitepaper/inde...   

                      hostname  \
0       belajarprogramming.com   
1              ninedotlabs.com   
2       www.almostfabulous.com   
3              stbcomputer.com   
4           members.tripod.com   
...                        ...   
95777           www.winehq.com   
95778              2933517.com   
95779         imajinsmiles.com   
95780  thesecondhalfonline.com   
95781  www.informationweek.com   

                                                    path  \
0                            /newpaypal/loggy/paypal.htm   
1                                        /att2/index.php   
2                                               /youker/   
3      /autodesk/components/www.paypal.com/dk/cgi-bin...   
4                                           /chang.ling/   
...                                                  ...   
95777                                                  /   
95778                                                /js   
95779                                    /Questions.html   
95780    /wp-includes/js/tinymce/remository.utilitie.htm   
95781                            /whitepaper/index.jhtml   

                                                   query  
0                                                         
1                                                         
2                                                         
3                                                         
4                                                         
...                                                  ...  
95777                                       interview=14  
95778                                                     
95779  cmd=_Questions&amp;dispatch=5885d80a13c0db1fb6...  
95780                                                     
95781                                       catID=200001  

[95782 rows x 7 columns]

In [8]:
urldata['host_path'] = urldata['hostname']+urldata['path']

In [9]:
urldata

index                                                url  label  \
0      30845  belajarprogramming.com/newpaypal/loggy/paypal.htm      1   
1      25750                     ninedotlabs.com/att2/index.php      1   
2      91832                     www.almostfabulous.com/youker/      0   
3      29165  stbcomputer.com/autodesk/components/www.paypal...      1   
4      52012                     members.tripod.com/chang.ling/      0   
...      ...                                                ...    ...   
95777  86523                       www.winehq.com/?interview=14      0   
95778  45352                                     2933517.com/js      1   
95779  34852  imajinsmiles.com/Questions.html?cmd=_Questions...      1   
95780   7754  thesecondhalfonline.com/wp-includes/js/tinymce...      1   
95781  79751  www.informationweek.com/whitepaper/index.jhtml...      0   

                                                   m_url  \
0      http://belajarprogramming.com/newpaypal/loggy/...   
1                  http://ninedotlabs.com/att2/index.php   
2                  http://www.almostfabulous.com/youker/   
3      http://stbcomputer.com/autodesk/components/www...   
4                  http://members.tripod.com/chang.ling/   
...                                                  ...   
95777                http://www.winehq.com/?interview=14   
95778                              http://2933517.com/js   
95779  http://imajinsmiles.com/Questions.html?cmd=_Qu...   
95780  http://thesecondhalfonline.com/wp-includes/js/...   
95781  http://www.informationweek.com/whitepaper/inde...   

                      hostname  \
0       belajarprogramming.com   
1              ninedotlabs.com   
2       www.almostfabulous.com   
3              stbcomputer.com   
4           members.tripod.com   
...                        ...   
95777           www.winehq.com   
95778              2933517.com   
95779         imajinsmiles.com   
95780  thesecondhalfonline.com   
95781  www.informationweek.com   

                                                    path  \
0                            /newpaypal/loggy/paypal.htm   
1                                        /att2/index.php   
2                                               /youker/   
3      /autodesk/components/www.paypal.com/dk/cgi-bin...   
4                                           /chang.ling/   
...                                                  ...   
95777                                                  /   
95778                                                /js   
95779                                    /Questions.html   
95780    /wp-includes/js/tinymce/remository.utilitie.htm   
95781                            /whitepaper/index.jhtml   

                                                   query  \
0                                                          
1                                                          
2                                                          
3                                                          
4                                                          
...                                                  ...   
95777                                       interview=14   
95778                                                      
95779  cmd=_Questions&amp;dispatch=5885d80a13c0db1fb6...   
95780                                                      
95781                                       catID=200001   

                                               host_path  
0      belajarprogramming.com/newpaypal/loggy/paypal.htm  
1                         ninedotlabs.com/att2/index.php  
2                         www.almostfabulous.com/youker/  
3      stbcomputer.com/autodesk/components/www.paypal...  
4                         members.tripod.com/chang.ling/  
...                                                  ...  
95777                                    www.winehq.com/  
95778                                     2933517.com/js  
95779          

In [10]:
domainNamesAll = urldata['host_path'].tolist()
LEncoder = LabelEncoder()
allCharacters = ''.join(domainNamesAll)
LEncoder.fit(list(allCharacters))
Lencoded_domainNames = []
Len_DM=[]
for d in domainNamesAll:
    # Split the domain name into a list of characters
    characters = list(d)
    # Encode each character as an integer using the LabelEncoder object
    encoded_characters = LEncoder.transform(characters)
    # Append the encoded characters to the list of encoded domain names
    Len_DM.append(len(encoded_characters))
    if len(encoded_characters) > 500:
        encoded_characters = encoded_characters[:500]
    Lencoded_domainNames.append(encoded_characters)
maxLength = max([len(encoded_domain_name) for encoded_domain_name in Lencoded_domainNames])
maxLength

500

In [14]:
Lencoded_domainNames

[array([59, 62, 69, 58, 67, 58, 75, 73, 75, 72, 64, 75, 58, 70, 70, 66, 71,
        64, 11, 60, 72, 70, 12, 71, 62, 80, 73, 58, 82, 73, 58, 69, 12, 69,
        72, 64, 64, 82, 12, 73, 58, 82, 73, 58, 69, 11, 65, 77, 70],
       dtype=int64),
 array([71, 66, 71, 62, 61, 72, 77, 69, 58, 59, 76, 11, 60, 72, 70, 12, 58,
        77, 77, 15, 12, 66, 71, 61, 62, 81, 11, 73, 65, 73], dtype=int64),
 array([80, 80, 80, 11, 58, 69, 70, 72, 76, 77, 63, 58, 59, 78, 69, 72, 78,
        76, 11, 60, 72, 70, 12, 82, 72, 78, 68, 62, 75, 12], dtype=int64),
 array([76, 77, 59, 60, 72, 70, 73, 78, 77, 62, 75, 11, 60, 72, 70, 12, 58,
        78, 77, 72, 61, 62, 76, 68, 12, 60, 72, 70, 73, 72, 71, 62, 71, 77,
        76, 12, 80, 80, 80, 11, 73, 58, 82, 73, 58, 69, 11, 60, 72, 70, 12,
        61, 68, 12, 60, 64, 66, 10, 59, 66, 71, 12, 80, 62, 59, 76, 60, 75,
        12, 60, 70, 61, 10, 69, 72, 64, 66, 71, 12, 15, 14, 19, 14, 16, 18,
        19, 22, 61, 20, 59, 58, 17, 21, 59, 20, 15, 61, 63, 13, 58, 18, 18,


In [11]:
num_unique_chars = len(LEncoder.classes_)
num_unique_chars

88

In [13]:
LEncoder.classes_

array([' ', '!', '$', '%', '&', '(', ')', '*', '+', ',', '-', '.', '/',
       '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '=',
       '@', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L',
       'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y',
       'Z', '[', '\\', ']', '^', '_', 'a', 'b', 'c', 'd', 'e', 'f', 'g',
       'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't',
       'u', 'v', 'w', 'x', 'y', 'z', '{', '|', '}', '~'], dtype='<U1')

In [12]:
from keras.preprocessing.sequence import pad_sequences
X = pad_sequences(Lencoded_domainNames, maxlen = maxLength)

In [13]:
Y = urldata['label']

In [14]:
len(X), len(Y)

(95782, 95782)

In [15]:
from sklearn.model_selection import train_test_split
Xtrain, Xtest, ytrain, ytest = train_test_split(X, Y, test_size=0.2, random_state=42)

In [16]:
Xtrain.shape, len(ytrain)

((76625, 500), 76625)

In [17]:
Xtest.shape, len(ytest)

((19157, 500), 19157)

In [18]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers.embeddings import Embedding
from keras.layers.convolutional import Conv1D
from keras.layers.convolutional import MaxPooling1D
from keras.layers import SpatialDropout1D
from keras.preprocessing import sequence
from keras.layers import Dropout
from keras.callbacks import EarlyStopping
from keras.layers import GaussianNoise
from keras.layers import Bidirectional
from keras.regularizers import l1, l2, l1_l2

In [19]:
vocab_size = num_unique_chars

In [20]:
model = Sequential()

model.add(Embedding(vocab_size, 100, input_length=maxLength))
model.add(Dropout(0.4))
model.add(GaussianNoise(0.5))
model.add(Bidirectional(LSTM(128, activation='tanh', recurrent_dropout=0.4))) #, kernel_regularizer=l2(l2=0.01)
model.add(Dense(64, activation='tanh'))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
print(model.summary())

import time
start=time.time()

history = model.fit(Xtrain, ytrain, validation_data=(Xtest, ytest), epochs=10, verbose=1) 
print('time for training the model = {:.0f} sec'.format(time.time()-start))
# evaluate
loss, acc = model.evaluate(Xtest, ytest, verbose=0)
print('Test Accuracy: %f' % (acc*100))
print('Test Loss: %f' % (loss*100))


Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 500, 100)          8800      
_________________________________________________________________
dropout (Dropout)            (None, 500, 100)          0         
_________________________________________________________________
gaussian_noise (GaussianNois (None, 500, 100)          0         
_________________________________________________________________
bidirectional (Bidirectional (None, 256)               234496    
_________________________________________________________________
dense (Dense)                (None, 64)                16448     
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 65        
Total params: 259,809
Trainable params: 259,809
Non-trainable params: 0
__________________________________________________

In [21]:
from sklearn.metrics import confusion_matrix
y_pred = model.predict(Xtest)
print(confusion_matrix(ytest, np.rint(y_pred)))

[[9461  126]
 [ 582 8988]]


In [22]:
model.save("../saved_models/Char-biLSTM_iter10.h5")